### ISSUE TITLE
Does not take tab position into consideration when replacing tabs

### ISSUE THREAD

**Issue by Kirdow** [patchon/remove-tabs-on-save#8]
I'm tried using this for some assembly programming I'm working on, and my VSCode is set to 4 spaces for viewing.
I'm sure this extension is made with only left hand tabs in mind, but with Assembly it's quite common to have tabs in between code segments to structure the code.

Take this block as an example:
```x86asm
    MOV     EAX, nVariable
    PUSH    EAX
    CALL    SomeFunc
    ADD     ESP, 4
```
After the MOV on the first line, the tab is at the 8th position (index 7), meaning it only adds 1 space visually, then another tabs adds 4 as usual, this means it renders 5 spaces. However, the extension currently replaces all tabs with 4 spaces no matter what, this means upon save, the above code now ends up looking like this:
```x86asm
    MOV        EAX, nVariable
    PUSH    EAX
    CALL    SomeFunc
    ADD        ESP, 4
```
As you can see, this isn't as readable, and it's also clearly different.

For most people this doesn't happen as C-Style code (C, Java, JS/TS etc) never really uses tabs other to indent the block itself, but for Assembly this gets noticed immediately.

A fix for this would be to take the tab column into consideration with something like ``const spaces = tabSize - (index % tabSize)``, although you may still need to run this in a ``replaceNext`` rather than ``replaceAll`` however that may be done with your implementation.

**Comment by patchon** [comment]
Oh, wow, do people use this plugin 😄 

I would be able to update this accordingly if you provide me with a working pr, I don't really have the time right now to do it myself (even though you have literally described what is needed to be done 🙇 🥳 ).

**Comment by patchon** [comment]
Hi,

Just wante to let you know that this issue should be fixed now.
Had to rewrite the whole extension, and went down the rabbit hole in another issue that bothered me for a long time. 
But hey, now its finished and *should* work, at least according to my initial testing. 

Thanks again for your feedback 🎉
